Support for AWS_DEFAULT_REGION env variable

diff --git a/ecs-wait-for-task b/ecs-wait-for-task
--- a/ecs-wait-for-task
+++ b/ecs-wait-for-task
@@ -60,9 +60,13 @@ function assertRequiredArgumentsSet() {
         exit 2
     fi
 
-	if [[ -z ${AWS_REGION+x} ]]; then
-        echo "AWS_REGION env variable is required."
-        exit 2
+    if [[ -z ${AWS_REGION+x} ]]; then
+        if [[ -z ${AWS_DEFAULT_REGION+x} ]]; then
+            echo "AWS_REGION or AWS_DEFAULT_REGION env variable is required."
+            exit 2
+        fi
+
+        AWS_REGION=${AWS_DEFAULT_REGION}
     fi
 
     if [[ ${AWS_CLUSTER} == false ]]; then
